"""empty message

Revision ID: 1218b76a6d5a
Revises: c9346579389e
Create Date: 2021-10-18 19:26:36.548473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1218b76a6d5a'
down_revision = 'c9346579389e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'comment', ['parent_comment_id'], ['id'])
    op.drop_column('comment', 'reply_to')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('reply_to', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'comment', ['reply_to'], ['id'])
    # ### end Alembic commands ###
