"""empty message

Revision ID: 8b78a82f82bb
Revises: c8dc12ea7528
Create Date: 2021-10-18 19:09:21.482251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b78a82f82bb'
down_revision = 'c8dc12ea7528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('parent_comment_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'comment', ['parent_comment_id'], ['id'])
    op.drop_column('comment', 'reply_to')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('reply_to', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'comment', ['reply_to'], ['id'])
    op.drop_column('comment', 'parent_comment_id')
    # ### end Alembic commands ###
