"""empty message

Revision ID: c9346579389e
Revises: 88ff45a622fa
Create Date: 2021-10-18 19:24:57.696686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9346579389e'
down_revision = '88ff45a622fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'comment', ['parent_comment_id'], ['id'])
    op.drop_column('comment', 'reply_to')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('reply_to', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'comment', ['reply_to'], ['id'])
    # ### end Alembic commands ###
