"""empty message

Revision ID: ce6c02e56238
Revises: 5669b48b8dcf
Create Date: 2021-10-18 19:43:58.964591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6c02e56238'
down_revision = '5669b48b8dcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'comment', ['parent_id'], ['id'])
    op.drop_column('comment', 'parent_comment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('parent_comment_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'comment', ['parent_comment_id'], ['id'])
    op.drop_column('comment', 'parent_id')
    # ### end Alembic commands ###
